### ISSUE TITLE
error in css? on make campaign

### ISSUE THREAD

**Issue by HerbWalsh** [sbwtech/sbw_campaigns#4]
when I activate the plugin the settings page seems alright but when I go to make a campaign it shows an unformatted page and has no save option. it is like the css is missing. Here is the error from the log:
2017/06/28 22:31:26 [error] 3545#3545: *1132 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'SebastianBergmann\Money\Currency' not found in /home/admin/web/mydomain.com/public_html/mod/payments/lib/functions.php on line 15" while reading response header from upstream, client: 70.27.20.212, server: mydomain.com, request: "GET /campaigns/add/36 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "mydomain.com", referrer: "https://mydomain.com/campaigns"

**Comment by HerbWalsh** [comment]
Installed releases of these plugins: https://github.com/hypeJunction/Elgg-payments/releases/tag/2.0.12 https://github.com/hypeJunction/Elgg-payments_paypal_api/releases/tag/1.0.3
now they work and swb_campaigns...is working as well.

**Comment by juho-jaakkola** [comment]
On the initial try your site was missing some dependencies. Closing the issue, as the problem seems to be fixed in the later versions.
